"""
Generate a C header containing a single binarized MNIST test image,
ready to be linked into the SNN end-to-end firmware.

Usage:
    python gen_mnist_header.py [IMAGE_INDEX]

Default index: 6767.

Only depends on numpy + Python stdlib (urllib, gzip). The first run
downloads the MNIST test-set IDX files (~1.6 MB) into ./mnist_cache/.

Output:
    mnist_img.h  in the project root.
"""
import gzip
import os
import sys
import urllib.request

IMAGE_INDEX = int(sys.argv[1]) if len(sys.argv) > 1 else 6767

CACHE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mnist_cache")
os.makedirs(CACHE_DIR, exist_ok=True)

# Mirror that doesn't rate-limit. ossci is the PyTorch CDN.
URLS = {
    "images": "https://ossci-datasets.s3.amazonaws.com/mnist/t10k-images-idx3-ubyte.gz",
    "labels": "https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz",
}

def fetch(name, url):
    path = os.path.join(CACHE_DIR, os.path.basename(url))
    if not os.path.exists(path):
        print(f"Downloading {name} -> {path}")
        urllib.request.urlretrieve(url, path)
    return path

img_path = fetch("images", URLS["images"])
lbl_path = fetch("labels", URLS["labels"])

with gzip.open(img_path, "rb") as f:
    f.read(16)  # magic + header
    img_data = f.read()
with gzip.open(lbl_path, "rb") as f:
    f.read(8)
    lbl_data = f.read()

# 784 raw grayscale bytes for the chosen image (pixel 0 first, row-major).
base       = IMAGE_INDEX * 784
img_bytes  = img_data[base:base + 784]
true_label = lbl_data[IMAGE_INDEX]

# Binarize: pixel > 127 -> spike (1).
flat_vector = [1 if b > 127 else 0 for b in img_bytes]  # 784 entries
active      = sum(flat_vector)

NUM_WORDS = 25  # ceil(784/32) = 25
words = [0] * NUM_WORDS
for pixel_idx, bit in enumerate(flat_vector):
    if bit:
        word = pixel_idx // 32
        lsb  = pixel_idx %  32
        words[word] |= (1 << lsb)

header = []
header.append(f"// Auto-generated by gen_mnist_header.py - do not edit.")
header.append(f"// MNIST test index {IMAGE_INDEX}, true label {true_label}, "
              f"{active} active pixels.")
header.append("#ifndef MNIST_IMG_H")
header.append("#define MNIST_IMG_H")
header.append("#include <stdint.h>")
header.append(f"#define MNIST_TRUE_LABEL  {true_label}")
header.append(f"#define MNIST_NUM_WORDS   {NUM_WORDS}")
header.append("static const uint32_t mnist_img[MNIST_NUM_WORDS] = {")
for w in words:
    header.append(f"    0x{w:08X}u,")
header.append("};")
header.append("#endif")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mnist_img.h")
with open(out_path, "w") as f:
    f.write("\n".join(header) + "\n")

print(f"Wrote {out_path}: MNIST[{IMAGE_INDEX}] label={true_label}, "
      f"{active} spikes, {NUM_WORDS} words.")
