// Auto-generated by gen_mnist_header.py - do not edit.
// MNIST test index 5555, true label 3, 163 active pixels.
#ifndef MNIST_IMG_H
#define MNIST_IMG_H
#include <stdint.h>
#define MNIST_TRUE_LABEL  3
#define MNIST_NUM_WORDS   25
static const uint32_t mnist_img[MNIST_NUM_WORDS] = {
    0x00000000u,
    0x00000000u,
    0x00000000u,
    0x00000000u,
    0xFF800000u,
    0x0FFF8000u,
    0x00FFFC00u,
    0x000707C0u,
    0x00007800u,
    0x000003C0u,
    0xF000003Eu,
    0xFFC00007u,
    0x1FFF0000u,
    0x03E1F800u,
    0x00380700u,
    0x00038000u,
    0x70003C00u,
    0x038001E0u,
    0xFE38001Fu,
    0x07FF8000u,
    0x001FF000u,
    0x00007E00u,
    0x00000000u,
    0x00000000u,
    0x00000000u,
};
#endif
