# -*- coding: utf-8 -*-
"""SNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfBoW3vi3q85lA9PUICIgAB7TCL3Ijw_
"""

# -*- coding: utf-8 -*-
"""SNN.ipynb — Modified for Combined Weight Memory Export

Memory layout (single 64-bit wide BRAM, depth 6400):
  - Layer 1 weights : addresses    0 – 6271  (6272 entries)
  - Layer 2 weights : addresses 6272 – 6399  (128 entries, offset = 6272)

Each address holds 8 × INT8 weights packed into one 64-bit word.
  Layer 1 : 6272 × 8 = 50 176 = 64 × 784  ✓
  Layer 2 :  128 × 8 =  1 024 ≥ 10 × 64 = 640  (zero-padded at the end)
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms
import snntorch as snn
from snntorch import surrogate
import numpy as np
import os
import sys

# --- 1. HYPERPARAMETERS ---
BATCH_SIZE = 128
LEARNING_RATE = 0.0005
EPOCHS = 50          # Keep it low for initial testing
NUM_STEPS = 1      # Clock cycles to simulate per image
BETA = 0.5          # Decay rate (Matches our hardware >> 1 shift)
THRESHOLD = 1.0     # Firing threshold

# --- Memory layout constants ---
L1_WEIGHTS_TOTAL  = 64 * 784      # 50 176  (fc1 flat weights)
L2_WEIGHTS_TOTAL  = 10 * 64       # 640     (fc2 flat weights)
WEIGHTS_PER_ADDR  = 8             # 64-bit word = 8 × INT8
L1_DEPTH          = L1_WEIGHTS_TOTAL // WEIGHTS_PER_ADDR   # 6 272
L2_DEPTH          = 128                                     # padded region size
L2_OFFSET         = L1_DEPTH                               # 6 272
TOTAL_DEPTH       = L2_OFFSET + L2_DEPTH                   # 6 400

# --- 2. DATASET (Standard MNIST) ---
print("Downloading/Loading MNIST Dataset...")
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Lambda(lambda x: x.view(-1)) # Flatten 28x28 into 784-element vector
])

train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# Split training into train/validation (80/20)
train_size = int(0.8 * len(train_dataset))
val_size = len(train_dataset) - train_size
train_dataset, val_dataset = random_split(train_dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# --- 3. THE SNN MODEL ---
class PureSoftwareSNN(nn.Module):
    def __init__(self):
        super().__init__()
        spike_grad = surrogate.fast_sigmoid(slope=25)

        # Hardware Target: 784 Inputs -> 64 Hidden -> 10 Outputs
        self.fc1 = nn.Linear(784, 64, bias=False) # Dropping bias to save hardware BRAM!
        self.lif1 = snn.Leaky(beta=BETA, threshold=THRESHOLD, spike_grad=spike_grad)

        self.fc2 = nn.Linear(64, 10, bias=False)
        self.lif2 = snn.Leaky(beta=BETA, threshold=THRESHOLD, spike_grad=spike_grad)

    def forward(self, x):
        mem1 = self.lif1.init_leaky()
        mem2 = self.lif2.init_leaky()

        spk2_rec = []

        for step in range(NUM_STEPS):
            cur1 = self.fc1(x)
            spk1, mem1 = self.lif1(cur1, mem1)

            cur2 = self.fc2(spk1)
            spk2, mem2 = self.lif2(cur2, mem2)

            spk2_rec.append(spk2)

        # Return the sum of spikes over time (for classification)
        return torch.stack(spk2_rec).sum(dim=0)

def evaluate(model, loader, device):
    """Evaluate model accuracy on a dataset."""
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for data, targets in loader:
            data = data.to(device)
            targets = targets.to(device)
            output = model(data)
            correct += (output.argmax(1) == targets).sum().item()
            total += targets.size(0)
    model.train()
    return 100 * correct / total

# --- 4. TRAINING LOOP ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on: {device}")

model = PureSoftwareSNN().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
loss_fn = nn.CrossEntropyLoss() # Standard classification loss

print("\n--- Starting Training ---")
best_val_acc = 0
for epoch in range(EPOCHS):
    total_loss = 0
    for i, (data, targets) in enumerate(train_loader):
        data = data.to(device)
        targets = targets.to(device)

        # Forward pass
        spk_counts = model(data)

        # Calculate loss and update weights
        loss = loss_fn(spk_counts, targets)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        if i % 100 == 0:
            print(f"Epoch {epoch+1}/{EPOCHS} | Batch {i}/{len(train_loader)} | Loss: {loss.item():.4f}")

    # Validation after each epoch
    val_acc = evaluate(model, val_loader, device)
    print(f"Epoch {epoch+1}/{EPOCHS} | Validation Accuracy: {val_acc:.2f}%")

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), 'best_snn_model.pth')
        print(f"  ✓ Best model saved (Val Acc: {val_acc:.2f}%)")

print("\n--- Training Complete! ---")

# Load best model and evaluate on test set
model.load_state_dict(torch.load('best_snn_model.pth'))
test_acc = evaluate(model, test_loader, device)
print(f"Test Accuracy: {test_acc:.2f}%")

# --- 5. HARDWARE EXTRACTION & PACKAGING ---
print("\n--- Packaging Weights for Physical SRAM ---")

def generate_hardware_hex(model, threshold_float, filename="weights_combined.hex"):
    # 1. Extract floats
    w1_float = model.fc1.weight.detach().cpu().numpy() # Shape: (64, 784)
    w2_float = model.fc2.weight.detach().cpu().numpy() # Shape: (10, 64)

    # 2. Calculate Scales and Quantize
    scale1 = 127.0 / np.max(np.abs(w1_float))
    w1_q = np.clip(np.round(w1_float * scale1), -128, 127).astype(np.int8)

    scale2 = 127.0 / np.max(np.abs(w2_float))
    w2_q = np.clip(np.round(w2_float * scale2), -128, 127).astype(np.int8)

    with open(filename, 'w') as f:
        # ---------------------------------------------------------
        # LAYER 1 SRAM MAPPING (Addresses 0 to 6271)
        # Hardware iterates through 784 pixels. For each pixel,
        # it fetches 8 words (64 lanes total for 64 hidden neurons)
        # ---------------------------------------------------------
        for p in range(784):
            for step in range(8):
                hex_word = ""
                for lane in range(8):
                    hidden_neuron_idx = step * 8 + lane
                    val = w1_q[hidden_neuron_idx, p]

                    # Verilog reads lane 0 as LSB. Prepend to build MSB->LSB.
                    hex_word = f"{int(val) & 0xFF:02X}" + hex_word
                f.write(f"{hex_word}\n")

        # ---------------------------------------------------------
        # LAYER 2 SRAM MAPPING (Addresses 6272 to 6399)
        # Hardware iterates through 64 Hidden Spikes. For each spike,
        # it fetches 2 words (16 lanes total for 10 output neurons)
        # ---------------------------------------------------------
        for h in range(64):
            # Word 0: Weights to Output Neurons 0-7
            hex_word_0 = ""
            for lane in range(8):
                val = w2_q[lane, h]
                hex_word_0 = f"{int(val) & 0xFF:02X}" + hex_word_0
            f.write(f"{hex_word_0}\n")

            # Word 1: Weights to Output Neurons 8-9 (plus 6 lanes of zero padding)
            hex_word_1 = ""
            for lane in range(8):
                out_neuron_idx = 8 + lane
                if out_neuron_idx < 10:
                    val = w2_q[out_neuron_idx, h]
                else:
                    val = 0 # Zero padding for physical lanes 10-15
                hex_word_1 = f"{int(val) & 0xFF:02X}" + hex_word_1
            f.write(f"{hex_word_1}\n")

    print(f"Success! Memory mapped to {filename}")
    print(f"--> IMPORTANT: Update Verilog THRESH_L1 to: {int(threshold_float * scale1)}")
    print(f"--> IMPORTANT: Update Verilog THRESH_L2 to: {int(threshold_float * scale2)}")

# Run the packager
generate_hardware_hex(model, THRESHOLD, "weights_combined.hex")

# --- 6. GOLDEN BIT-ACCURATE HARDWARE SIMULATION ---
def evaluate_hardware_accurate(model, loader, device, threshold_float):
    """
    Golden Reference Model.
    Simulates exact RTL behavior using integers and bit-shifts.
    Uses the SAME quantization scales as the combined memory export.
    """
    model.eval()
    correct = 0
    total = 0

    # Extract and Quantize Weights to INT8 (must match combined export scales)
    w1_float = model.fc1.weight.detach().cpu()
    w2_float = model.fc2.weight.detach().cpu()

    _scale1 = 127.0 / torch.max(torch.abs(w1_float))
    w1_q = torch.clamp(torch.round(w1_float * _scale1), -128, 127).to(torch.int32)

    _scale2 = 127.0 / torch.max(torch.abs(w2_float))
    w2_q = torch.clamp(torch.round(w2_float * _scale2), -128, 127).to(torch.int32)

    # Scale thresholds to match quantized weight domain
    thresh1_q = int(threshold_float * _scale1)
    thresh2_q = int(threshold_float * _scale2)

    print(f"Hardware L1 Threshold: {thresh1_q}")
    print(f"Hardware L2 Threshold: {thresh2_q}")

    with torch.no_grad():
        for data, targets in loader:
            # Binary spike input (>0.5 → 1)
            data_int = (data > 0.5).to(torch.int32)

            batch_size = data.size(0)

            # Scratchpad memories (membrane potentials)
            mem1_spm = torch.zeros((batch_size, 64), dtype=torch.int32)
            mem2_spm = torch.zeros((batch_size, 10), dtype=torch.int32)
            spk2_sum = torch.zeros((batch_size, 10), dtype=torch.int32)

            for step in range(NUM_STEPS):
                # --- LAYER 1 (addresses 0 – 6271 in combined mem) ---
                cur1 = torch.matmul(data_int, w1_q.t())
                mem1_spm = torch.bitwise_right_shift(mem1_spm, 1)  # Beta=0.5
                mem1_spm = mem1_spm + cur1
                spk1 = (mem1_spm >= thresh1_q).to(torch.int32)
                mem1_spm[spk1 == 1] = 0                            # Hard reset

                # --- LAYER 2 (addresses 6272 – 6399 in combined mem) ---
                cur2 = torch.matmul(spk1, w2_q.t())
                mem2_spm = torch.bitwise_right_shift(mem2_spm, 1)  # Beta=0.5
                mem2_spm = mem2_spm + cur2
                spk2 = (mem2_spm >= thresh2_q).to(torch.int32)
                mem2_spm[spk2 == 1] = 0                            # Hard reset

                spk2_sum += spk2

            predictions = spk2_sum.argmax(dim=1)
            correct += (predictions == targets).sum().item()
            total += targets.size(0)

    return 100 * correct / total

# Run Golden Model Check
print("\n--- Running Golden Bit-Accurate Hardware Simulation ---")
hw_acc = evaluate_hardware_accurate(model, test_loader, 'cpu', THRESHOLD)
print(f"Bit-Accurate Hardware Accuracy: {hw_acc:.2f}%")
print("Done")

# --- 7. COLAB FILE DOWNLOAD ---
try:
    from google.colab import files
    print("\n--- Downloading files from Colab ---")

    # Download the PyTorch model
    files.download('best_snn_model.pth')

    # Download the combined hardware memory file directly!
    files.download('weights_combined.hex')

except ImportError:
    print("Not running in Colab, skipping file download")

