`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 22.12.2025 21:52:05
// Design Name: 
// Module Name: riscv_top
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module riscv_top(
    // PS7 FIXED_IO — required for Zynq PL startup
    inout [53:0] FIXED_IO_mio,
    inout        FIXED_IO_ps_clk,
    inout        FIXED_IO_ps_porb,
    inout        FIXED_IO_ps_srstb,

    output [4:0] gpr_data_o,

    // UART serial I/O for FPGA (115200 8-N-1)
    output        uart_tx_o,
    input         uart_rx_i
    );
    // Simulation-only probes — internal wires, not top-level ports.
    // coremark_tb accesses these via hierarchical path (dut.uart_valid_o etc.)
    wire        uart_valid_o;
    wire [7:0]  uart_char_o;

    // ILA debug probes
    (* mark_debug = "true", KEEP = "TRUE" *) wire        dbg_uart_tx_valid;
    (* mark_debug = "true", KEEP = "TRUE" *) wire        dbg_uart_tx_pre;
    (* mark_debug = "true", KEEP = "TRUE" *) wire        dbg_rstn;
    (* mark_debug = "true", KEEP = "TRUE" *) wire [14:0] dbg_pc;
    (* mark_debug = "true", KEEP = "TRUE" *) wire        dbg_uart_addr;
    (* mark_debug = "true", KEEP = "TRUE" *) wire [7:0]  dbg_uart_char;
    
    // SNN accelerator — driven by CPU CSRs 0xBC0..0xBC5.
    //   exec.csr writes  : snn_img_base (0xBC0), snn_kick (0xBC2)
    //   exec.csr reads   : snn_output_spike (0xBC3), snn_hidden_spike (0xBC4/5)
    //   snn_top reads DTCM via memory_stage port B (snn_dtcm_*)
    wire [11:0] snn_img_base;
    wire        snn_kick;

    wire        snn_dtcm_rd_en;
    wire [11:0] snn_dtcm_addr;
    wire [31:0] snn_dtcm_data;

    wire        snn_done;
    wire [9:0]  snn_output_spike;
    wire [63:0] snn_hidden_spike;

    // SNN accelerator instance. Kicked by CSR 0xBC2; reads the input image
    // from DTCM via memory_stage port B (snn_dtcm_*); returns classification
    // (output_spike) and hidden-layer activity (hidden_spike) to the CPU via
    // CSR reads. snn_done = done_layer2_o (L2 classification complete); the
    // L1 and learning done flags are unused in the inference-only flow.
    // timestep_i tags spikes for STDP timing; inference uses a fixed tag.
    snn_top #(
        .WEIGHT_WIDTH   (8),
        .TIMESTEP_WIDTH (8)
    ) snn (
        .clk_i          (clk),
        .rstn_i         (rstn),
        .timestep_i     (8'd1),
        .snn_kick_i     (snn_kick),
        .img_base_i     (snn_img_base),
        .hidden_spike_o (snn_hidden_spike),
        .output_spike_o (snn_output_spike),
        .done_layer1_o  (),
        .done_layer2_o  (snn_done),
        .done_learn_o   (),
        .dtcm_rd_en_o   (snn_dtcm_rd_en),
        .dtcm_addr_o    (snn_dtcm_addr),
        .dtcm_data_i    (snn_dtcm_data)
    );
    
    `include "defs.v"

    // ---------------------------------------------------------------
    // PS7 — provides FCLK0 (100 MHz) and active-low PL reset
    // ---------------------------------------------------------------
    wire fclk0, ps_rstn_n;

    ps_stub_wrapper u_ps_stub (
        .FCLK_CLK0_0      (fclk0),
        .FCLK_RESET0_N_0  (ps_rstn_n),
        .FIXED_IO_mio     (FIXED_IO_mio),
        .FIXED_IO_ps_clk  (FIXED_IO_ps_clk),
        .FIXED_IO_ps_porb (FIXED_IO_ps_porb),
        .FIXED_IO_ps_srstb(FIXED_IO_ps_srstb)
    );

    // Clock: PS7 FCLK0 = 100 MHz, generated by PS PLLs.
    // No external oscillator needed — PS clock is always available.
    wire clk;
    BUFG u_clk_buf (.I(fclk0), .O(clk));

    // POR: hold reset while PS is not ready (ps_rstn_n low), then release
    // after 8 clock cycles once PS asserts ps_rstn_n high.
    (* SHREG_EXTRACT = "NO" *) reg [7:0] por_sr = 8'hFF;
    always @(posedge clk or negedge ps_rstn_n)
        if (!ps_rstn_n) por_sr <= 8'hFF;
        else            por_sr <= {por_sr[6:0], 1'b0};
    wire rstn = ~por_sr[7];

    // UART RX input
    wire uart_rx_buf;
    IBUF u_uart_rx_ibuf (.I(uart_rx_i), .O(uart_rx_buf));

    // UART TX output (driven internally, buffered to pad)
    wire uart_tx_pre;
    OBUF u_uart_tx_obuf (.I(uart_tx_pre), .O(uart_tx_o));

    // GPR data outputs (5 LEDs)
    wire [4:0] gpr_pre;
    OBUF u_gpr_obuf [4:0] (.I(gpr_pre), .O(gpr_data_o));

    //Control Unit Wire (direct feedback from execute stage)
    (* mark_debug = "true", KEEP = "TRUE" *) wire        trap_trigger;
    wire [1:0]  fe_pc_sel;
    
    //Fetch Stage Wire
    wire [31:0] fe_instr;
    wire [31:0] fe_pc;
    wire [31:0] fe_pc_plus4;
    
    //Decode Stage Wire
    wire          dec_regfile_we;
    wire          dec_branch_en;
    wire          dec_jump_en;
    wire          dec_jump_ctrl;
    wire          dec_lsu_en;
    wire          dec_alu_en;
    wire          dec_csr_rwe;
    wire          dec_mux_rs1;
    wire          dec_mux_imm;
    wire          dec_ecall;
    wire          dec_mret;
    wire          dec_illegal_instr;
    wire [1:0]    dec_result_src;
    wire [2:0]    dec_branch_ctrl;
    wire [2:0]    dec_csr_ctrl;
    wire [3:0]    dec_lsu_ctrl;
    wire [3:0]    dec_alu_ctrl;
    wire [4:0]    dec_rs1;
    wire [4:0]    dec_rs2;
    wire [4:0]    dec_rd;
    wire [31:0]   dec_data_rs1;
    wire [31:0]   dec_data_rs2;
    wire [31:0]   dec_signext;
    wire [31:0]   dec_pc;
    wire [31:0]   dec_pc_plus4;
    
    //Execute Stage Wire
    wire        exec_pc_taken;
    wire        exec_dtcm_wr_en;
    wire        exec_dtcm_rd_en;
    wire        exec_regfile_we;
    wire [1:0]  exec_ld_ext_ctrl;
    wire [1:0]  exec_result_src;
    wire [3:0]  exec_mask;
    wire        exec_lh_cross;
    wire        exec_sh_cross;
    wire [4:0]  exec_rd;
    wire [29:0] exec_dtcm_addr;
    wire [31:0] exec_dtcm_data;
    wire [31:0] exec_result;
    wire [31:0] exec_pctarget;
    wire [31:0] exec_branch_csr;
    wire [31:0] exec_wb_csr;
    wire [31:0] exec_pc_plus4;
    
    //Memory Stage Wire
    wire        mem_regfile_we;
    wire [1:0]  mem_result_src;
    wire [4:0]  mem_rd;
    wire [31:0] mem_pc_plus4;
    wire [31:0] mem_alu_result;
    wire [31:0] mem_ld_data;
    wire [31:0] mem_wb_csr;
    wire [31:0] mem_pctarget;
    
    //Writeback Wire
    wire [31:0] wb_result;
    
    //Fetch/Decode Reg
    reg [31:0]  reg_fe_instr; 
    reg [31:0]  reg_fe_pc;
    reg [31:0]  reg_fe_pc_plus4;
    
    //Decode/Exec Reg
    reg         reg_dec_regfile_we;
    reg         reg_dec_branch_en;
    reg         reg_dec_jump_en;
    reg         reg_dec_jump_ctrl;
    reg         reg_dec_lsu_en;
    reg         reg_dec_alu_en;
    reg         reg_dec_csr_rwe;
    reg         reg_dec_mux_rs1;
    reg         reg_dec_mux_imm;
    reg         reg_dec_ecall;
    reg         reg_dec_mret;
    reg         reg_dec_illegal_instr;
    reg [1:0]   reg_dec_result_src;
    reg [2:0]   reg_dec_branch_ctrl;
    reg [2:0]   reg_dec_csr_ctrl;
    reg [3:0]   reg_dec_lsu_ctrl;
    reg [3:0]   reg_dec_alu_ctrl;
    reg [4:0]   reg_dec_rs1;
    reg [4:0]   reg_dec_rs2;
    reg [4:0]   reg_dec_rd;
    reg [31:0]  reg_dec_data_rs1;
    reg [31:0]  reg_dec_data_rs2;
    reg [31:0]  reg_dec_signext;
    (* mark_debug = "true", KEEP = "TRUE" *) reg [31:0]  reg_dec_pc;
    reg [31:0]  reg_dec_pc_plus4;
    
    //Exec/Mem Reg
    reg         reg_exec_dtcm_wr_en;
    reg         reg_exec_dtcm_rd_en;
    reg         reg_exec_regfile_we;
    reg [1:0]   reg_exec_ld_ext_ctrl;
    reg [1:0]   reg_result_src;
    reg [3:0]   reg_exec_mask;
    reg         reg_exec_lh_cross;
    reg         reg_exec_sh_cross;
    reg [4:0]   reg_exec_rd;
    reg [29:0]  reg_exec_dtcm_addr;
    reg [31:0]  reg_exec_dtcm_data;
    reg [31:0]  reg_exec_result;
    reg [31:0]  reg_exec_pctarget;
    reg [31:0]  reg_exec_branch_csr;
    reg [31:0]  reg_exec_wb_csr;
    reg [31:0]  reg_exec_pc_plus4;

    // MEM-stage forwarding source: mirror writeback_stage's mux so that
    // CSR / PC+4 results are forwarded, not just the ALU result.
    // result_src encoding: 00=CSR, 01=ALU, 10=PC+4, 11=LD (load-use stalls).
    wire [31:0] mem_forward_result =
        reg_result_src[1] ? (reg_result_src[0] ? 32'h0          : reg_exec_pc_plus4) :
                            (reg_result_src[0] ? reg_exec_result : reg_exec_wb_csr);

    //Mem/Writeback Reg
    reg         reg_wb_regfile_we;
    reg [1:0]   reg_wb_result_src;
    reg [4:0]   reg_wb_rd;
    reg [31:0]  reg_wb_pc_plus4;
    reg [31:0]  reg_wb_alu_result;
    reg [31:0]  reg_wb_ld_data;
    reg [31:0]  reg_wb_csr;

    // Heartbeat — increments only when rstn is high (reset-dependent, kept for ILA)
    (* DONT_TOUCH = "TRUE" *) reg [23:0]  heartbeat_cnt;

    // Free-running counter — NO reset. Proves fclk0 reaches flip-flops
    // regardless of whether ps_rstn_n ever asserts.
    // bit[25] toggles at ~1.5 Hz (2^26 / 100 MHz = 0.67 s period).
    (* DONT_TOUCH = "TRUE" *) reg [25:0]  free_cnt;

    //Hazard Unit Wire
    wire [1:0] hzrd_mux_rs1;
    wire [1:0] hzrd_mux_rs2;
    wire       hzrd_stall;

    // BRAM 1-cycle wait-state stall: fires once per load entering MEM stage.
    // mem_bram_valid is only set when BRAM actually received rd_en (not suppressed by sh_cross).
    reg  mem_bram_valid;
    wire mem_rd_stall = (reg_exec_dtcm_rd_en & ~is_uart_addr) & ~mem_bram_valid;
    wire mem_stall    = mem_rd_stall | sh_cross_pending;
    always @(posedge clk or negedge rstn) begin
        if (~rstn)               mem_bram_valid <= 1'b0;
        else if (mem_rd_stall && mem_dtcm_rd_in) mem_bram_valid <= 1'b1; // BRAM sampled
        else                     mem_bram_valid <= 1'b0;
    end

    // sh_cross secondary write: addr+1 byte is written one cycle after the primary SH write
    reg        sh_cross_pending;
    reg [29:0] sh_pend_addr;
    reg [7:0]  sh_pend_data;
    always @(posedge clk or negedge rstn) begin
        if (~rstn) begin
            sh_cross_pending <= 1'b0;
        end else begin
            // only latch once; ~sh_cross_pending prevents re-firing while pipeline is frozen
            sh_cross_pending <= (reg_exec_dtcm_wr_en & reg_exec_sh_cross & ~is_uart_addr) & ~sh_cross_pending;
            sh_pend_addr     <= reg_exec_dtcm_addr + 30'd1;
            sh_pend_data     <= reg_exec_dtcm_data[7:0];
        end
    end
    
    //Fetch Stage
    fetch_stage fe(
    //Input
    .clk_i(clk),
    .rstn_i(rstn),
    .pc_stall_i(hzrd_stall | mem_stall),
    .pc_sel_i(fe_pc_sel),
    .pctarget_i(exec_pctarget),
    .branch_csr_i(exec_branch_csr),
    //Output
    .instr_o(fe_instr),
    .pc_o(fe_pc),
    .pc_plus4_o(fe_pc_plus4)
    );
    
    decode_stage dec (
    //Input
    .clk_i(clk),
    .rstn_i(rstn),
    .wb_regfile_wr_en_i(reg_wb_regfile_we), //Deleted Trap_trigger and stall inputs
    .wb_rd_i(reg_wb_rd),
    .wb_mem_i(wb_result),
    .instr_i(reg_fe_instr),
    .pc_i(reg_fe_pc),
    .pc_plus4_i(reg_fe_pc_plus4),
    //Output
    .data_rs1_o(dec_data_rs1),
    .data_rs2_o(dec_data_rs2),
    .dec_regfile_we_o(dec_regfile_we),
    .wb_result_src_o(dec_result_src),
    .exec_branch_en_o(dec_branch_en),
    .exec_jump_en_o(dec_jump_en),
    .exec_jump_ctrl_o(dec_jump_ctrl),
    .exec_lsu_en_o(dec_lsu_en),
    .exec_alu_en_o(dec_alu_en),
    .exec_csr_rwe_o(dec_csr_rwe),
    .exec_mux_rs1_o(dec_mux_rs1),
    .exec_mux_imm_o(dec_mux_imm),
    .exec_branch_ctrl_o(dec_branch_ctrl),
    .exec_csr_ctrl_o(dec_csr_ctrl),
    .exec_lsu_ctrl_o(dec_lsu_ctrl),
    .exec_alu_ctrl_o(dec_alu_ctrl),
    .exec_ecall_o(dec_ecall),
    .exec_mret_o(dec_mret),
    .illegal_instr_o(dec_illegal_instr),
    .signext_o(dec_signext),
    .rs1_o(dec_rs1),
    .rs2_o(dec_rs2),
    .rd_o(dec_rd),
    .pc_o(dec_pc),
    .pc_plus4_o(dec_pc_plus4)
    );
    
    execute_stage exec(
    //Input
    .clk_i(clk),
    .rstn_i(rstn),
    .data_rs1_i(reg_dec_data_rs1),
    .data_rs2_i(reg_dec_data_rs2),
    .exec_branch_en_i(reg_dec_branch_en),
    .exec_jump_en_i(reg_dec_jump_en),
    .exec_jump_ctrl_i(reg_dec_jump_ctrl),
    .exec_lsu_en_i(reg_dec_lsu_en),
    .exec_alu_en_i(reg_dec_alu_en),
    .exec_csr_rwe_i(reg_dec_csr_rwe),
    .exec_mux_rs1_i(reg_dec_mux_rs1),
    .exec_mux_imm_i(reg_dec_mux_imm),
    .exec_branch_ctrl_i(reg_dec_branch_ctrl),
    .exec_csr_ctrl_i(reg_dec_csr_ctrl),
    .exec_lsu_ctrl_i(reg_dec_lsu_ctrl),
    .exec_alu_ctrl_i(reg_dec_alu_ctrl),
    .exec_ecall_i(reg_dec_ecall),
    .exec_mret_i(reg_dec_mret),
    .illegal_instr_i(reg_dec_illegal_instr),
    .mux_rs1_i(hzrd_mux_rs1),
    .mux_rs2_i(hzrd_mux_rs2),
    .signext_i(reg_dec_signext),
    .rs1_i(reg_dec_rs1),
    .pc_i(reg_dec_pc),
    .pc_plus4_i(reg_dec_pc_plus4),
    .mem_result_i(mem_forward_result),
    .wb_result_i(wb_result),
    .exec_regfile_we_i(reg_dec_regfile_we),
    .exec_wb_result_src_i(reg_dec_result_src),
    .exec_rd_i(reg_dec_rd),
    //Output
    .pc_taken_o(exec_pc_taken),
    .pctarget_o(exec_pctarget),
    .alu_result_o(exec_result),
    .dtcm_data_o(exec_dtcm_data),
    .dtcm_addr_o(exec_dtcm_addr),
    .mask_o(exec_mask),
    .ld_ext_ctrl_o(exec_ld_ext_ctrl),
    .dtcm_rd_en_o(exec_dtcm_rd_en),
    .dtcm_wr_en_o(exec_dtcm_wr_en),
    .lh_cross_o(exec_lh_cross),
    .sh_cross_o(exec_sh_cross),
    .wb_csr_o(exec_wb_csr),
    .branch_csr_o(exec_branch_csr),
    .trap_trigger_o(trap_trigger),
    .exec_regfile_we_o(exec_regfile_we),
    .exec_wb_result_src_o(exec_result_src),
    .exec_rd_o(exec_rd),
    .exec_pc_plus4_o(exec_pc_plus4),
    .snn_img_base_o(snn_img_base),
    .snn_kick_o(snn_kick),
    .snn_done_i(snn_done),
    .snn_output_spike_i(snn_output_spike),
    .snn_hidden_spike_i(snn_hidden_spike)
    );
    
    // UART address decode — matches only 0x40000000 (TX data) and 0x40000004 (TX status).
    // reg_exec_dtcm_addr[29:1] == byte_addr[31:3]; for 0x40000000 this equals 0x8000000.
    // Old single-bit check (addr[28]) matched any address with bit 30 set, causing
    // false UART triggers and suppressed DTCM writes during benchmark computation.
    wire is_uart_addr       = (reg_exec_dtcm_addr[29:1] == 29'h8000000);
    wire is_uart_status_rd  = is_uart_addr & reg_exec_dtcm_addr[0] & reg_exec_dtcm_rd_en;

    // UART TX hardware
    wire uart_tx_valid = reg_exec_dtcm_wr_en & is_uart_addr & ~reg_exec_dtcm_addr[0];
    wire uart_tx_busy;  // tx_full from AXI UARTLite (16-byte FIFO full flag)

    axi_uart_bridge u_axi_uart_bridge (
        .clk_i       (clk),
        .rstn_i      (rstn),
        .cpu_wr_en   (uart_tx_valid),
        .cpu_wr_data (reg_exec_dtcm_data[7:0]),
        .tx_full_o   (uart_tx_busy),
        .uart_tx_o   (uart_tx_pre),
        .uart_rx_i   (uart_rx_buf)
    );

    // sh_cross: mux in pending secondary write (addr+1, byte 0) one cycle after primary SH
    wire [29:0] mem_dtcm_addr_in = sh_cross_pending ? sh_pend_addr               : reg_exec_dtcm_addr;
    wire [31:0] mem_dtcm_data_in = sh_cross_pending ? {24'b0, sh_pend_data}      : reg_exec_dtcm_data;
    wire [3:0]  mem_dtcm_mask_in = sh_cross_pending ? 4'b0001                    : reg_exec_mask;
    wire        mem_dtcm_wr_in   = sh_cross_pending ? 1'b1 : (reg_exec_dtcm_wr_en & ~is_uart_addr);
    wire        mem_dtcm_rd_in   = sh_cross_pending ? 1'b0 : (reg_exec_dtcm_rd_en & ~is_uart_addr);

    memory_stage mem (
    //Input
    .clk_i(clk),
    .rstn_i(rstn),
    .dtcm_data_i(mem_dtcm_data_in),
    .dtcm_addr_i(mem_dtcm_addr_in),
    .mask_i(mem_dtcm_mask_in),
    .ld_ext_ctrl_i(reg_exec_ld_ext_ctrl),
    .dtcm_rd_en_i(mem_dtcm_rd_in),
    .dtcm_wr_en_i(mem_dtcm_wr_in),
    .lh_cross_i(reg_exec_lh_cross),
    .mem_regfile_we_i(reg_exec_regfile_we),
    .mem_wb_result_src_i(reg_result_src),
    .mem_rd_i(reg_exec_rd),
    .mem_pc_plus4_i(reg_exec_pc_plus4),
    .mem_alu_result_i(reg_exec_result),
    .mem_pctarget_i(reg_exec_pctarget),
    .mem_wb_csr_i(reg_exec_wb_csr),
    //Output
    .ld_data_o(mem_ld_data),
    .mem_regfile_we_o(mem_regfile_we),
    .mem_wb_result_src_o(mem_result_src),
    .mem_rd_o(mem_rd),
    .mem_pc_plus4_o(mem_pc_plus4),
    .mem_alu_result_o(mem_alu_result),
    .mem_pctarget_o(mem_pctarget),
    .mem_wb_csr_o(mem_wb_csr),
    .snn_rd_en_i(snn_dtcm_rd_en),
    .snn_addr_i(snn_dtcm_addr),
    .snn_data_o(snn_dtcm_data)
    );
    
    writeback_stage wb (
    .wb_src_i(reg_wb_result_src),
    .wb_csr_o(reg_wb_csr),
    .wb_alu_result_o(reg_wb_alu_result),
    .wb_ld_o(reg_wb_ld_data),
    .wb_pc_plus4_o(reg_wb_pc_plus4),
    .wb_result_o(wb_result)
    );
    
    hazardunit hzrd (
    .dec_rs1_i(dec_rs1),
    .dec_rs2_i(dec_rs2),
    .exec_rs1_i(reg_dec_rs1),
    .exec_rs2_i(reg_dec_rs2),
    .exec_rd_i(exec_rd),
    .mem_rd_i(mem_rd),
    .wb_rd_i(reg_wb_rd),
    .dtcm_rd_i(exec_dtcm_rd_en),
    .exec_regfile_we_i(reg_exec_regfile_we),
    .wb_regfile_we_i(reg_wb_regfile_we),
    .mux_rs1_o(hzrd_mux_rs1),
    .mux_rs2_o(hzrd_mux_rs2),
    .stall_o(hzrd_stall)
    );
    
    //FETCH/DECODE Register
    always @ (posedge clk or negedge rstn) begin
        if(~rstn) begin
            reg_fe_instr    <= `NOP;
            reg_fe_pc       <= 32'h0;
            reg_fe_pc_plus4 <= 32'h0;
        end
        else if (trap_trigger || exec_pc_taken) begin
            reg_fe_instr    <= `NOP;
            reg_fe_pc       <= 32'h0;
            reg_fe_pc_plus4 <= 32'h0;
        end
        else if (!hzrd_stall && !mem_stall) begin
            reg_fe_instr    <= fe_instr;
            reg_fe_pc       <= fe_pc;
            reg_fe_pc_plus4 <= fe_pc_plus4;
        end
   end
   
   //DECODE/EXECUTE Register
   always @ (posedge clk or negedge rstn) begin
        if(~rstn) begin
            reg_dec_regfile_we <= 1'b0;
            reg_dec_branch_en <= 1'b0;
            reg_dec_jump_en <= 1'b0;
            reg_dec_jump_ctrl <= 1'b1;
            reg_dec_lsu_en <= 1'b0;
            reg_dec_alu_en <= 1'b0;
            reg_dec_csr_rwe <= 1'b0;
            reg_dec_mux_rs1 <= 1'b0;
            reg_dec_mux_imm <= 1'b0;
            reg_dec_ecall <= 1'b0;
            reg_dec_mret <= 1'b0;
            reg_dec_illegal_instr <= 1'b0;
            reg_dec_result_src <= 2'b01; //Default ALU Result writeback
            reg_dec_branch_ctrl <= 3'b010; //Default Case Statement
            reg_dec_csr_ctrl <= 3'b000; //Default Case Statement
            reg_dec_lsu_ctrl <= 4'b1111; //Default Case Statement
            reg_dec_alu_ctrl <= `ALU_ADD; //Default ADD
            reg_dec_rs1 <= 5'b0;
            reg_dec_rs2 <= 5'b0;
            reg_dec_rd <= 5'b0;
            reg_dec_data_rs1 <= 32'h0;
            reg_dec_data_rs2 <= 32'h0;
            reg_dec_signext <= 32'h0;
            reg_dec_pc <= 32'h0;
            reg_dec_pc_plus4 <= 32'h0;
       end
       else if (mem_stall) begin
            // whole-pipeline freeze: hold DE/EX register (implicit — no assignment)
       end
       else if (trap_trigger || exec_pc_taken || hzrd_stall) begin
            reg_dec_regfile_we  <= 1'b0;
            reg_dec_branch_en   <= 1'b0;
            reg_dec_jump_en     <= 1'b0;
            reg_dec_lsu_en      <= 1'b0;
            reg_dec_alu_en      <= 1'b0;
            reg_dec_csr_rwe     <= 1'b0;
       end
       else begin
            reg_dec_regfile_we <= dec_regfile_we;
            reg_dec_branch_en <= dec_branch_en;
            reg_dec_jump_en <= dec_jump_en;
            reg_dec_jump_ctrl <= dec_jump_ctrl;
            reg_dec_lsu_en <= dec_lsu_en;
            reg_dec_alu_en <= dec_alu_en;
            reg_dec_csr_rwe <= dec_csr_rwe;
            reg_dec_mux_rs1 <= dec_mux_rs1;
            reg_dec_mux_imm <= dec_mux_imm;
            reg_dec_ecall <= dec_ecall;
            reg_dec_mret <= dec_mret;
            reg_dec_illegal_instr <= dec_illegal_instr;
            reg_dec_result_src <= dec_result_src;
            reg_dec_branch_ctrl <= dec_branch_ctrl;
            reg_dec_csr_ctrl <= dec_csr_ctrl;
            reg_dec_lsu_ctrl <= dec_lsu_ctrl;
            reg_dec_alu_ctrl <= dec_alu_ctrl;
            reg_dec_rs1 <= dec_rs1;
            reg_dec_rs2 <= dec_rs2;
            reg_dec_rd <= dec_rd;
            reg_dec_data_rs1 <= dec_data_rs1;
            reg_dec_data_rs2 <= dec_data_rs2;
            reg_dec_signext <= dec_signext;
            reg_dec_pc <= dec_pc;
            reg_dec_pc_plus4 <= dec_pc_plus4;
       end
   end
   
   //EXECUTE/MEM Register
   always @ (posedge clk or negedge rstn) begin
        if(~rstn) begin
            reg_exec_dtcm_wr_en <= 1'b0;
            reg_exec_dtcm_rd_en <= 1'b0;
            reg_exec_regfile_we <= 1'b0;
            reg_exec_ld_ext_ctrl <= 2'b00;
            reg_result_src <= 2'b01; //Default ALU Result
            reg_exec_mask <= 4'b0;
            reg_exec_lh_cross <= 1'b0;
            reg_exec_rd <= 5'b0;
            reg_exec_dtcm_addr <= 29'h0;
            reg_exec_dtcm_data <= 32'h0;
            reg_exec_result <= 32'h0;
            reg_exec_pctarget <= 32'h0;
            reg_exec_wb_csr <= 32'h0;
            reg_exec_pc_plus4 <= 32'h0;
        end
        else if (trap_trigger) begin
            reg_exec_dtcm_wr_en     <= 1'b0;
            reg_exec_dtcm_rd_en     <= 1'b0;
            reg_exec_regfile_we     <= 1'b0;
            reg_exec_lh_cross       <= 1'b0;
            reg_exec_sh_cross       <= 1'b0;
        end
        else if (mem_stall) begin
            // whole-pipeline freeze: hold EX/MEM register (implicit)
        end
        else begin
            reg_exec_dtcm_wr_en <= exec_dtcm_wr_en;
            reg_exec_dtcm_rd_en <= exec_dtcm_rd_en;
            reg_exec_regfile_we <= exec_regfile_we;
            reg_exec_ld_ext_ctrl <= exec_ld_ext_ctrl;
            reg_result_src <= exec_result_src;
            reg_exec_mask <= exec_mask;
            reg_exec_lh_cross <= exec_lh_cross;
            reg_exec_sh_cross <= exec_sh_cross;
            reg_exec_rd <= exec_rd;
            reg_exec_dtcm_addr <= exec_dtcm_addr;
            reg_exec_dtcm_data <= exec_dtcm_data;
            reg_exec_result <= exec_result;
            reg_exec_pctarget <= exec_pctarget;
            reg_exec_wb_csr <= exec_wb_csr;
            reg_exec_pc_plus4 <= exec_pc_plus4;
       end
   end
   
   //MEM/WB Register
   always @ (posedge clk or negedge rstn) begin
        if(~rstn) begin
            reg_wb_regfile_we <= 1'b0;
            reg_wb_result_src <= 2'b01; //Default ALU result
            reg_wb_rd <= 5'b0;
            reg_wb_pc_plus4 <= 32'h0;
            reg_wb_alu_result <= 32'h0;
            reg_wb_ld_data <= 32'h0;
            reg_wb_csr <= 32'h0;
       end
       else if (trap_trigger) begin
            reg_wb_regfile_we <= 1'b0;
       end
       else if (mem_stall) begin
            // whole-pipeline freeze: hold MEM/WB register (implicit)
       end
       else begin
            reg_wb_regfile_we <= mem_regfile_we;
            reg_wb_result_src <= mem_result_src;
            reg_wb_rd <= mem_rd;
            reg_wb_pc_plus4 <= mem_pc_plus4;
            reg_wb_alu_result <= mem_alu_result;
            reg_wb_ld_data <= is_uart_status_rd ? {31'b0, uart_tx_busy} : mem_ld_data;
            reg_wb_csr <= mem_wb_csr;
       end
   end
   
   // Heartbeat counter — increments every clock; bit 23 toggles at ~6 Hz (100 MHz / 2^24)
   always @(posedge clk or negedge rstn)
       if (~rstn) heartbeat_cnt <= 24'd0;
       else       heartbeat_cnt <= heartbeat_cnt + 24'd1;

   // Free-running counter — absolutely no reset signal. If fclk0 reaches FFs,
   // free_cnt[25] blinks ~1.5 Hz on T16 regardless of ps_rstn_n state.
   always @(posedge clk)
       free_cnt <= free_cnt + 26'd1;

   //Combinational (Final PC Selection Logic)
   assign fe_pc_sel = (trap_trigger) ? `FE_BRANCH_CSR :
                      (exec_pc_taken) ? `FE_PC_TARGET : `FE_PC_PLUS4;

   // Activity LED on T16 (gpr_data_o[0]):
   //   blinks ~1.5 Hz while CoreMark is producing UART output, latches solid ON
   //   ~670 ms after the last uart_tx_valid pulse (run finished).
   reg  [25:0] quiet_cnt;
   reg         uart_started;
   reg         run_done;
   always @(posedge clk or negedge rstn) begin
       if (!rstn) begin
           quiet_cnt    <= 26'd0;
           uart_started <= 1'b0;
           run_done     <= 1'b0;
       end else if (uart_tx_valid) begin
           uart_started <= 1'b1;
           quiet_cnt    <= 26'd0;
       end else if (uart_started && !run_done) begin
           if (&quiet_cnt) run_done  <= 1'b1;
           else            quiet_cnt <= quiet_cnt + 26'd1;
       end
   end
   wire led_activity = run_done ? 1'b1 : free_cnt[25];

   //Output Assignment
   assign gpr_pre      = {4'b0, led_activity};
   assign uart_valid_o = uart_tx_valid;          // sim probe: fires when byte written
   assign uart_char_o  = reg_exec_dtcm_data[7:0];

   // ILA debug assignments
   assign dbg_uart_tx_valid = uart_tx_valid;
   assign dbg_uart_tx_pre   = uart_tx_pre;
   assign dbg_rstn          = rstn;
   assign dbg_pc            = fe_pc[14:0];
   assign dbg_uart_addr     = is_uart_addr;
   assign dbg_uart_char     = reg_exec_dtcm_data[7:0];

endmodule
