# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.srcs/sources_1/ip/axi_uart/axi_uart.xci
# IP: The module: 'axi_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.gen/sources_1/ip/axi_uart/axi_uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uart'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.gen/sources_1/ip/axi_uart/axi_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.srcs/sources_1/ip/axi_uart/axi_uart.xci
# IP: The module: 'axi_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.gen/sources_1/ip/axi_uart/axi_uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.gen/sources_1/ip/axi_uart/axi_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
