# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/riscv_const.xdc

# Block Designs: bd/ps_stub/ps_stub.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_stub || ORIG_REF_NAME==ps_stub} -quiet] -quiet

# IP: bd/ps_stub/ip/ps_stub_ps7_0_0/ps_stub_ps7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_stub_ps7_0_0 || ORIG_REF_NAME==ps_stub_ps7_0_0} -quiet] -quiet

# XDC: c:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.gen/sources_1/bd/ps_stub/ps_stub_ooc.xdc
