# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.srcs/sources_1/bd/ps_stub/ip/ps_stub_ps7_0_0/ps_stub_ps7_0_0.xci
# IP: The module: 'ps_stub_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.gen/sources_1/bd/ps_stub/ip/ps_stub_ps7_0_0/ps_stub_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_stub_ps7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.srcs/sources_1/bd/ps_stub/ip/ps_stub_ps7_0_0/ps_stub_ps7_0_0.xci
# IP: The module: 'ps_stub_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Documents/FYP_Docs/RISCV_SNN/RISCV_SNN.gen/sources_1/bd/ps_stub/ip/ps_stub_ps7_0_0/ps_stub_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_stub_ps7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
